name: bantenprov_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# ===================== DEPENDENCIES =====================
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  table_calendar: ^3.0.9

# ===================== DEV DEPENDENCIES =====================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ===================== FLUTTER CONFIG =====================
flutter:
  uses-material-design: true

  assets:
    # logo & background
    - assets/images/LogoUmah_Banten.png
    - assets/images/LogoBanten.png
    - assets/images/Background_Banten.png
    - assets/images/Logobantenataskanan.png
    - assets/images/logokabupaten.png

    # kegiatan
    - assets/images/kegiatan1.png
    - assets/images/kegiatan2.png

    # main background
    - assets/images/Backgroundmain.png
    - assets/images/Backgroundmain2.png
    - assets/images/beritaInformasiHome.png

    # event
    - assets/images/event1.png
    - assets/images/event2.png

    # galeri
    - assets/images/galeri1.png
    - assets/images/galeri2.png
    - assets/images/galeri3.png
    - assets/images/galeri4.png
    - assets/images/galeri5.png
    - assets/images/galeri6.png
    - assets/images/galeri7.png
    - assets/images/galeri8.png

    # login & laporan
    - assets/images/bglogin.png
    - assets/images/logoUmahBantenpolos.png
    - assets/images/bg_galeri.png
    - assets/images/laporan1.png
    - assets/images/laporan2.png
    - assets/images/laporan3.png
    - assets/images/laporan4.png

    # cctv
    - assets/images/IconCCTV1.png
    - assets/images/IconCCTVbener.png
    - assets/images/IconCCTVbenerbg.png

    # umum
    - assets/images/fingerprint.png
    - assets/images/umum2.png
    - assets/images/umum3.png
    - assets/images/umum4.png
    - assets/images/umum5.png
    - assets/images/umum6.png
    - assets/images/umum7.png
    - assets/images/umum8.png
    - assets/images/umum9.png
    

    # monitoring
    - assets/images/monitoring1.png
    - assets/images/monitoring2.png
    - assets/images/monitoring3.png
    - assets/images/monitoring4fix.png

    # administrator
    - assets/images/admin1.png
    - assets/images/admin2.png
    - assets/images/admin3.png

    # menu
    - assets/images/menu1.png
    - assets/images/menu2.png
    - assets/images/menu3.png
    - assets/images/menu4.png
    - assets/images/menu5.png
    - assets/images/menu6.png
    - assets/images/menu7.png

    # umum
    - assets/images/hibah_bansos.png
    - assets/images/jadwal_dokter.png
    - assets/images/span_lapor.png
    - assets/images/cctv.png
    - assets/images/lpse.png
    - assets/images/wbs.png
    - assets/images/pkb.png
    - assets/images/menara_banten.png
    - assets/images/siloker.png
    - assets/images/csirt.png
    - assets/images/bumilfit.png
    - assets/images/pendaftaran_pasien.png
    - assets/images/sibenda.png
    - assets/images/simanis2.png
    - assets/images/laju_pkb.png
    - assets/images/aduan_konten.png
    - assets/images/rekrutment.png
    - assets/images/skm.png
    - assets/images/sipelaku.png
    - assets/images/antrisamsat.png
    - assets/images/sisi_baja.png
    - assets/images/sitatap.png
    - assets/images/esapa.png
    - assets/images/simparda.png
    - assets/images/etoko_pkk.png
    - assets/images/rsud_malimping.png
    - assets/images/damkar.png
    - assets/images/antri_samsat.png
    - assets/images/ikm_bapenda.png
    - assets/images/background_publik.jpg

# data
    - assets/images/jdih.png
    - assets/images/satu_data.png
    - assets/images/eppid.png
    - assets/images/gistaru.png
    - assets/images/sipagi.png
    - assets/images/edasawisma.png
    - assets/images/open_data.png
    - assets/images/jdih_dprd.png
    - assets/images/sidakep.png
    - assets/images/batu_pusaka.png
    - assets/images/sidakbanten3.png

# kabupaten kota
    - assets/images/kabupaten_lebak.png
    - assets/images/kabupaten_pandeglang.png
    - assets/images/kabupaten_serang.png
    - assets/images/kabupaten_tangerang.png
    - assets/images/kota_cilegon.png
    - assets/images/kota_serang.png
    - assets/images/kota_tangerang.png
    - assets/images/kota_tangerang_selatan.png

# perizinan
    - assets/images/sipeka.png
    - assets/images/oss.png
    - assets/images/potensi_investasi.png
    - assets/images/sipitak.png
    - assets/images/perizinan_lingkungan.png

# profile
    - assets/images/jonggunpark.jpeg

# kalender & berita
    - assets/images/ppbanten.png
    - assets/images/backgroundkalender.png
    - assets/images/berita1.png
    - assets/images/berita2.png
    - assets/images/berita3.png
    - assets/images/berita4.png
    - assets/images/berita5.png
    - assets/images/berita6.png

# share
    - assets/images/wa.png
    - assets/images/zoom.png
    - assets/images/drive.png
    - assets/images/instagram.png
    - assets/images/gmail.png
    - assets/images/facebook.png
    - assets/images/line.png
    - assets/images/onedrive.png
    - assets/images/chrome.png
    - assets/images/telegram.png
    - assets/images/teams.png
    - assets/images/twitter.png

# ===================== APP ICON CONFIG =====================
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoBanten.png"
