name: bantenprov_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# ===================== DEPENDENCIES =====================
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.0
  table_calendar: ^3.0.9

# ===================== DEV DEPENDENCIES =====================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# ===================== FLUTTER CONFIG =====================
flutter:
  uses-material-design: true

  assets:
    # logo & background
    - assets/images/LogoUmah_Banten.png
    - assets/images/LogoBanten.png
    - assets/images/Background_Banten.png
    - assets/images/Logobantenataskanan.png
    - assets/images/logokabupaten.png

    # kegiatan
    - assets/images/kegiatan1.png
    - assets/images/kegiatan2.png

    # main background
    - assets/images/Backgroundmain.png
    - assets/images/Backgroundmain2.png
    - assets/images/beritaInformasiHome.png

    # event
    - assets/images/event1.png
    - assets/images/event2.png

    # galeri
    - assets/images/galeri1.png
    - assets/images/galeri2.png
    - assets/images/galeri3.png
    - assets/images/galeri4.png
    - assets/images/galeri5.png
    - assets/images/galeri6.png
    - assets/images/galeri7.png
    - assets/images/galeri8.png

    # login & laporan
    - assets/images/bglogin.png
    - assets/images/logoUmahBantenpolos.png
    - assets/images/bg_galeri.png
    - assets/images/laporan1.png
    - assets/images/laporan2.png
    - assets/images/laporan3.png
    - assets/images/laporan4.png

    # cctv
    - assets/images/IconCCTV1.png
    - assets/images/IconCCTVbener.png
    - assets/images/IconCCTVbenerbg.png

    # umum
    - assets/images/fingerprint.png
    - assets/images/umum2.png
    - assets/images/umum3.png
    - assets/images/umum4.png
    - assets/images/umum5.png
    - assets/images/umum6.png
    - assets/images/umum7.png
    - assets/images/umum8.png
    - assets/images/umum9.png

    # monitoring
    - assets/images/monitoring1.png
    - assets/images/monitoring2.png
    - assets/images/monitoring3.png
    - assets/images/monitoring4fix.png

    # administrator
    - assets/images/admin1.png
    - assets/images/admin2.png
    - assets/images/admin3.png

    # menu
    - assets/images/menu1.png
    - assets/images/menu2.png
    - assets/images/menu3.png
    - assets/images/menu4.png
    - assets/images/menu5.png
    - assets/images/menu6.png
    - assets/images/menu7.png

# ===================== APP ICON CONFIG =====================
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoBanten.png"
